from django.urls import path
from .views import (
    AddRecipeToShoppingListView,
    CalendarEventDetailView,
    CalendarEventListCreateView,
    CleaningLogDetailView,
    CleaningLogListCreateView,
    CleaningTaskDetailView,
    CleaningTaskListCreateView,
    ExportWeekToShoppingListView,
    ExternalMealGuestDetailView,
    ExternalMealGuestListCreateView,
    HouseholdMemberDetailView,
    HouseholdMemberListCreateView,
    IngredientDetailView,
    IngredientListView,
    MemberAvailabilityDetailView,
    MemberAvailabilityListCreateView,
    MenuDetailView,
    MenuListCreateView,
    RecalculateMenuPersonsView,
    RecipeDetailView,
    RecipeListCreateView,
    ShoppingItemDetailView,
    ShoppingItemListCreateView,
    ShoppingSuggestionView,
    TodoDetailView,
    TodoListCreateView,
    UserMealAttendanceView,
)

urlpatterns = [
    path('ingredients/', IngredientListView.as_view()),
    path('ingredients/<int:id>/', IngredientDetailView.as_view()),
    path('todos/', TodoListCreateView.as_view()),
    path('todos/<uuid:id>/', TodoDetailView.as_view()),
    path('recipes/', RecipeListCreateView.as_view()),
    path('recipes/<uuid:id>/', RecipeDetailView.as_view()),
    path('menus/', MenuListCreateView.as_view()),
    path('menus/<uuid:id>/', MenuDetailView.as_view()),
    path('menus/recalculate-persons/', RecalculateMenuPersonsView.as_view()),
    path('household-members/', HouseholdMemberListCreateView.as_view()),
    path('household-members/<uuid:id>/', HouseholdMemberDetailView.as_view()),
    path('member-availabilities/', MemberAvailabilityListCreateView.as_view()),
    path('member-availabilities/<uuid:id>/', MemberAvailabilityDetailView.as_view()),
    path('meal-attendance/', UserMealAttendanceView.as_view()),
    path('external-meal-guests/', ExternalMealGuestListCreateView.as_view()),
    path('external-meal-guests/<uuid:id>/', ExternalMealGuestDetailView.as_view()),
    path('shopping-items/', ShoppingItemListCreateView.as_view()),
    path('shopping-items/add-recipe/', AddRecipeToShoppingListView.as_view()),
    path('shopping-items/suggestions/', ShoppingSuggestionView.as_view()),
    path('shopping-items/export-week/', ExportWeekToShoppingListView.as_view()),
    path('shopping-items/<uuid:id>/', ShoppingItemDetailView.as_view()),
    path('calendar-events/', CalendarEventListCreateView.as_view()),
    path('calendar-events/<uuid:id>/', CalendarEventDetailView.as_view()),
    path('cleaning-tasks/', CleaningTaskListCreateView.as_view()),
    path('cleaning-tasks/<uuid:id>/', CleaningTaskDetailView.as_view()),
    path('cleaning-tasks/<uuid:task_id>/logs/', CleaningLogListCreateView.as_view()),
    path('cleaning-logs/<uuid:id>/', CleaningLogDetailView.as_view()),
]
