# Generated by Django 6.0 on 2026-07-01 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cooking_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('ease_rating', models.IntegerField(blank=True, null=True)),
                ('price_performance_rating', models.IntegerField(blank=True, null=True)),
                ('taste_rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='dinner_persons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch_persons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='suggestion',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurrence',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurrence_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_menu_per_user_date'),
        ),
        migrations.AddField(
            model_name='menurating',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='features.menu'),
        ),
    ]
