# Generated by Django 6.0 on 2026-07-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_todo_description_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notecategory',
            name='household',
        ),
        migrations.RemoveField(
            model_name='notecategory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='NoteCategory',
        ),
    ]
