# Generated by Django 6.0 on 2026-07-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_remove_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('gemuese', 'Gemüse'), ('obst', 'Obst'), ('fleisch', 'Fleisch & Fisch'), ('milch', 'Milchprodukte'), ('getreide', 'Getreide & Backwaren'), ('huelsenfruechte', 'Hülsenfrüchte'), ('gewuerze', 'Gewürze & Kräuter'), ('oele', 'Öle & Fette'), ('saucen', 'Saucen & Konserven'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20)),
                ('default_unit', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
