# Generated by Django 6.0 on 2026-07-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_recipe_steps_ingredient_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
