# Generated by Django 6.0 on 2026-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_recipe_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='base_servings',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_type',
            field=models.CharField(default='Portionen', max_length=20),
        ),
    ]
