# Generated by Django 6.0 on 2026-07-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_recipe_base_servings_recipe_serving_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='side_notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
