# Generated by Django 6.0 on 2026-07-02 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_recipe_side_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='breakfast_leftovers_ref',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='breakfast_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_menus', to='features.recipe'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dinner_leftovers_ref',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch_leftovers_ref',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
