# Generated by Django 6.0 on 2026-07-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_todo_created_by_meal_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermealattendance',
            name='breakfast_present',
            field=models.BooleanField(default=False),
        ),
    ]
