# Generated by Django 6.0 on 2026-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_external_meal_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='units_per_person',
            field=models.FloatField(default=1.0),
        ),
    ]
