# Generated by Django 6.0 on 2026-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0019_units_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='extra_recipe_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('mahlzeit', 'Mahlzeit'), ('dessert', 'Dessert'), ('backen', 'Backen'), ('snack', 'Snack'), ('beilage', 'Beilage'), ('sonstiges', 'Sonstiges')], default='mahlzeit', max_length=20),
        ),
    ]
