# Generated by Django 6.0 on 2026-10-07 17:15

import django.db.models.deletion
import uuid
import math
from django.db import migrations, models


def name_key(value):
    import unicodedata
    return unicodedata.normalize('NFKC', ' '.join(str(value).split())).casefold()


def forward(apps, schema_editor):
    Recipe = apps.get_model('features', 'Recipe')
    Amount = apps.get_model('features', 'RecipeIngredient')
    Section = apps.get_model('features', 'RecipeSection')
    Step = apps.get_model('features', 'RecipeStep')
    Link = apps.get_model('features', 'RecipeStepIngredient')
    Note = apps.get_model('features', 'RecipeNote')
    for amount in Amount.objects.all():
        amount.key = uuid.uuid4(); amount.save(update_fields=['key'])
    for recipe in Recipe.objects.iterator():
        sections = {}
        for position, value in enumerate(recipe.sections or []):
            if value['id'] in sections:
                raise ValueError(f'Rezept {recipe.id}: doppelte Abschnitts-ID.')
            sections[value['id']] = Section.objects.create(recipe=recipe, key=value['id'], title=value['title'], position=position)
        amounts = list(Amount.objects.filter(recipe=recipe).select_related('ingredient'))
        for amount in amounts:
            if amount.section_id is not None and amount.section_id not in sections:
                raise ValueError(f'Rezept {recipe.id}: unbekannter Zutatenabschnitt.')
            amount.section_ref = sections.get(amount.section_id); amount.save(update_fields=['section_ref'])
        for order, value in enumerate(sorted(recipe.steps or [], key=lambda v: v.get('order', 0)), 1):
            section_id = value.get('sectionId')
            if section_id is not None and section_id not in sections:
                raise ValueError(f'Rezept {recipe.id}: unbekannter Schrittabschnitt.')
            step = Step.objects.create(recipe=recipe, order=order, description=value.get('description', ''), section=sections.get(section_id))
            values = value.get('ingredients') or []
            if not values and value.get('ingredientName'):
                values = [{'name':value['ingredientName'], 'quantityPerPerson':value.get('quantityPerPerson'), 'unit':value.get('unit','')}]
            used = set()
            for position, link in enumerate(values):
                matches = [a for a in amounts if name_key(a.name) == name_key(link.get('name', '')) or (a.ingredient_id and a.ingredient_id == link.get('ingredientId'))]
                local = [a for a in matches if a.section_ref_id == step.section_id]
                options = local or matches
                if len(options) != 1:
                    raise ValueError(f'Rezept {recipe.id}: Schrittzutat {link.get("name", "")} kann nicht eindeutig zugeordnet werden.')
                amount = options[0]
                if amount.id in used:
                    raise ValueError(f'Rezept {recipe.id}: doppelte Zutat im Kochschritt.')
                used.add(amount.id)
                quantity = link.get('quantityPerPerson')
                if quantity == '': quantity = None
                if quantity is not None:
                    quantity = float(quantity)
                    if not math.isfinite(quantity) or quantity < 0:
                        raise ValueError(f'Rezept {recipe.id}: ungültige Schrittmenge.')
                Link.objects.create(step=step, recipe_ingredient=amount, quantity=quantity, unit=link.get('unit') or '', position=position)
        Note.objects.bulk_create([Note(recipe=recipe, label=value.get('label',''), value=value.get('value',''), position=position) for position, value in enumerate(recipe.side_notes or [])])


def backward(apps, schema_editor):
    Recipe = apps.get_model('features', 'Recipe')
    Amount = apps.get_model('features', 'RecipeIngredient')
    Section = apps.get_model('features', 'RecipeSection')
    Step = apps.get_model('features', 'RecipeStep')
    Link = apps.get_model('features', 'RecipeStepIngredient')
    Note = apps.get_model('features', 'RecipeNote')
    for recipe in Recipe.objects.all():
        recipe.sections = [{'id':r.key, 'title':r.title} for r in Section.objects.filter(recipe_id=recipe.pk)]
        recipe.side_notes = [{'label':r.label, 'value':r.value} for r in Note.objects.filter(recipe_id=recipe.pk)]
        steps = []
        for step in Step.objects.filter(recipe_id=recipe.pk).select_related('section'):
            value = {'order':step.order, 'description':step.description, 'ingredients':[]}
            if step.section_id: value['sectionId'] = step.section.key
            for link in Link.objects.filter(step_id=step.pk).select_related('recipe_ingredient__ingredient'):
                amount = link.recipe_ingredient
                value['ingredients'].append({'name':amount.ingredient.name if amount.ingredient_id else amount.name,
                    'quantityPerPerson': link.quantity if link.quantity is not None else amount.quantity, 'unit':link.unit or amount.unit})
            steps.append(value)
        recipe.steps = steps; recipe.save(update_fields=['sections', 'steps', 'side_notes'])
        for amount in Amount.objects.filter(recipe_id=recipe.pk).select_related('section_ref'):
            amount.section_id = amount.section_ref.key if amount.section_ref_id else None
            amount.save(update_fields=['section_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0024_relational_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='key',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.CreateModel(
            name='RecipeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('position', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_rows', to='features.recipe')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RecipeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('position', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_rows', to='features.recipe')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='section_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='features.recipesection'),
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_rows', to='features.recipe')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='features.recipesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_links', to='features.recipeingredient')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_links', to='features.recipestep')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipesection',
            constraint=models.UniqueConstraint(fields=('recipe', 'key'), name='unique_recipe_section_key'),
        ),
        migrations.AddConstraint(
            model_name='recipestep',
            constraint=models.UniqueConstraint(fields=('recipe', 'order'), name='unique_recipe_step_order'),
        ),
        migrations.AddConstraint(
            model_name='recipestepingredient',
            constraint=models.UniqueConstraint(fields=('step', 'recipe_ingredient'), name='unique_step_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipestepingredient',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gte', 0), _connector='OR'), name='step_ingredient_nonnegative_quantity'),
        ),
        migrations.RunPython(forward, backward),
        migrations.AlterField(model_name='recipeingredient', name='key', field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
        migrations.RemoveField(
            model_name='recipe',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='side_notes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='section_id',
        ),
    ]
