# Generated by Django 6.0 on 2026-10-07 18:19

from django.db import migrations, models


def mark_incomplete(apps, schema_editor):
    Item = apps.get_model('features', 'ShoppingItem')
    Item.objects.filter(quantity__isnull=True).update(quantity_incomplete=True)
    Item.objects.filter(suggestion__endswith=' · Menge im Rezept prüfen').update(quantity_incomplete=True)


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0025_structured_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='quantity_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_incomplete, migrations.RunPython.noop),
    ]
